export enum USER_ROLES {
  SUPER_ADMIN = "SUPER_ADMIN",
  ADMIN = "ADMIN",
  VENDOR = "VENDOR",
  USER = "USER",
}
export enum USER_STATUS {
  BLOCKED = "BLOCKED",
  ACTIVE = "ACTIVE",
  INACTIVE = "INACTIVE",
  PENDING = "PENDING",
  DELETED = "DELETED",
  SUSPENDED = "SUSPENDED",
  BANNED = "BANNED",
}
