export enum USER_ROLES {
  SUPER_ADMIN = "SUPER_ADMIN",
  ADMIN = "ADMIN",
  SERVICE_PROVIDER = "SERVICE_PROVIDER",
  USER = "USER",
  HOSPITALITY_VENUE = "HOSPITALITY_VENUE"
}
export enum USER_STATUS {
  BLOCKED = "BLOCKED",
  ACTIVE = "ACTIVE",
  INACTIVE = "INACTIVE",
  PENDING = "PENDING",
  DELETED = "DELETED",
  SUSPENDED = "SUSPENDED",
  BANNED = "BANNED"
}
